name: Weather data collector

on:
  schedule:
    - cron: '0 * * * *'       # kas valandą
  workflow_dispatch:         # rankiniam paleidimui

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        run: python weather.py

      - name: Commit CSV file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.csv
          git commit -m "Automated update $(date -u '+%Y-%m-%d %H:%M:%S') UTC" || echo "Nothing to commit"
          git push
