name: Weather data collector

# ši sekcija leidžia Actions bot’ui rašyti į repozitoriją
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'     # kas valandą, minutės 0
  workflow_dispatch:       # rankinis paleidimas, jei reikia

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        run: python weather.py

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.csv
          git commit -m "Automated update $(date -u '+%Y-%m-%d %H:%M:%S') UTC" || echo "Nothing to commit"
          git push
